// GENERADO por script (sesión 3-ago): roster ampliado con iconos autohospedados.
// Fuentes: fantendo (Smash), supercombo/sf-fandom (SF6), tekken-fandom+wavu (Tekken 8),
// Riot Data Dragon (LoL), valorant-api (Valorant), PokeAPI (Pokémon). No editar a mano:
// personajes.ts lo fusiona con el catálogo curado (que manda en caso de duplicado).
// OJO si se regenera: fantendo es una wiki FANON — la descarga metió 25 personajes
// inventados/no jugables (Slay the Spire, Hollow Knight, alts de Steve, trofeos ayudante…);
// smash está filtrado a mano al roster oficial de SSBU (85 + Pyra/Mythra en el curado).
export const PERSONAJES_GEN: Record<string, { nombre: string; img: string }[]> = {
  smash: [
    { nombre: 'Banjo-Kazooie', img: '/personajes/smash/banjo-kazooie.png' },
    { nombre: 'Bayonetta', img: '/personajes/smash/bayonetta.png' },
    { nombre: 'Bowser', img: '/personajes/smash/bowser.png' },
    { nombre: 'Bowser Jr.', img: '/personajes/smash/bowser-jr.png' },
    { nombre: 'Byleth', img: '/personajes/smash/byleth.png' },
    { nombre: 'Captain Falcon', img: '/personajes/smash/captain-falcon.png' },
    { nombre: 'Chrom', img: '/personajes/smash/chrom.png' },
    { nombre: 'Cloud', img: '/personajes/smash/cloud.png' },
    { nombre: 'Corrin', img: '/personajes/smash/corrin.png' },
    { nombre: 'Daisy', img: '/personajes/smash/daisy.png' },
    { nombre: 'Dark Pit', img: '/personajes/smash/dark-pit.png' },
    { nombre: 'Dark Samus', img: '/personajes/smash/dark-samus.png' },
    { nombre: 'Diddy Kong', img: '/personajes/smash/diddy-kong.png' },
    { nombre: 'Donkey Kong', img: '/personajes/smash/donkey-kong.png' },
    { nombre: 'Dr. Mario', img: '/personajes/smash/dr-mario.png' },
    { nombre: 'Duck Hunt', img: '/personajes/smash/duck-hunt.png' },
    { nombre: 'Falco', img: '/personajes/smash/falco.png' },
    { nombre: 'Fox', img: '/personajes/smash/fox.png' },
    { nombre: 'Ganondorf', img: '/personajes/smash/ganondorf.png' },
    { nombre: 'Greninja', img: '/personajes/smash/greninja.png' },
    { nombre: 'Hero', img: '/personajes/smash/hero.png' },
    { nombre: 'Ice Climbers', img: '/personajes/smash/ice-climbers.png' },
    { nombre: 'Ike', img: '/personajes/smash/ike.png' },
    { nombre: 'Incineroar', img: '/personajes/smash/incineroar.png' },
    { nombre: 'Inkling', img: '/personajes/smash/inkling.png' },
    { nombre: 'Isabelle', img: '/personajes/smash/isabelle.png' },
    { nombre: 'Jigglypuff', img: '/personajes/smash/jigglypuff.png' },
    { nombre: 'Joker', img: '/personajes/smash/joker.png' },
    { nombre: 'Kazuya', img: '/personajes/smash/kazuya.png' },
    { nombre: 'Ken', img: '/personajes/smash/ken.png' },
    { nombre: 'King Dedede', img: '/personajes/smash/king-dedede.png' },
    { nombre: 'King K. Rool', img: '/personajes/smash/king-k-rool.png' },
    { nombre: 'Kirby', img: '/personajes/smash/kirby.png' },
    { nombre: 'Link', img: '/personajes/smash/link.png' },
    { nombre: 'Little Mac', img: '/personajes/smash/little-mac.png' },
    { nombre: 'Lucario', img: '/personajes/smash/lucario.png' },
    { nombre: 'Lucas', img: '/personajes/smash/lucas.png' },
    { nombre: 'Lucina', img: '/personajes/smash/lucina.png' },
    { nombre: 'Luigi', img: '/personajes/smash/luigi.png' },
    { nombre: 'Mario', img: '/personajes/smash/mario.png' },
    { nombre: 'Marth', img: '/personajes/smash/marth.png' },
    { nombre: 'Mega Man', img: '/personajes/smash/mega-man.png' },
    { nombre: 'Meta Knight', img: '/personajes/smash/meta-knight.png' },
    { nombre: 'Mewtwo', img: '/personajes/smash/mewtwo.png' },
    { nombre: 'Mii Brawler', img: '/personajes/smash/mii-brawler.png' },
    { nombre: 'Mii Gunner', img: '/personajes/smash/mii-gunner.png' },
    { nombre: 'Mii Swordfighter', img: '/personajes/smash/mii-swordfighter.png' },
    { nombre: 'Min Min', img: '/personajes/smash/min-min.png' },
    { nombre: 'Mr. Game & Watch', img: '/personajes/smash/mr-game-watch.png' },
    { nombre: 'Ness', img: '/personajes/smash/ness.png' },
    { nombre: 'Olimar', img: '/personajes/smash/olimar.png' },
    { nombre: 'Pac-Man', img: '/personajes/smash/pac-man.png' },
    { nombre: 'Palutena', img: '/personajes/smash/palutena.png' },
    { nombre: 'Peach', img: '/personajes/smash/peach.png' },
    { nombre: 'Pichu', img: '/personajes/smash/pichu.png' },
    { nombre: 'Pikachu', img: '/personajes/smash/pikachu.png' },
    { nombre: 'Piranha Plant', img: '/personajes/smash/piranha-plant.png' },
    { nombre: 'Pit', img: '/personajes/smash/pit.png' },
    { nombre: 'Pokémon Trainer', img: '/personajes/smash/pok-mon-trainer.png' },
    { nombre: 'R.O.B.', img: '/personajes/smash/r-o-b.png' },
    { nombre: 'Richter', img: '/personajes/smash/richter.png' },
    { nombre: 'Ridley', img: '/personajes/smash/ridley.png' },
    { nombre: 'Robin', img: '/personajes/smash/robin.png' },
    { nombre: 'Rosalina', img: '/personajes/smash/rosalina.png' },
    { nombre: 'Roy', img: '/personajes/smash/roy.png' },
    { nombre: 'Ryu', img: '/personajes/smash/ryu.png' },
    { nombre: 'Samus', img: '/personajes/smash/samus.png' },
    { nombre: 'Sephiroth', img: '/personajes/smash/sephiroth.png' },
    { nombre: 'Sheik', img: '/personajes/smash/sheik.png' },
    { nombre: 'Shulk', img: '/personajes/smash/shulk.png' },
    { nombre: 'Simon', img: '/personajes/smash/simon.png' },
    { nombre: 'Snake', img: '/personajes/smash/snake.png' },
    { nombre: 'Sonic', img: '/personajes/smash/sonic.png' },
    { nombre: 'Sora', img: '/personajes/smash/sora.png' },
    { nombre: 'Steve', img: '/personajes/smash/steve.png' },
    { nombre: 'Terry', img: '/personajes/smash/terry.png' },
    { nombre: 'Toon Link', img: '/personajes/smash/toon-link.png' },
    { nombre: 'Villager', img: '/personajes/smash/villager.png' },
    { nombre: 'Wario', img: '/personajes/smash/wario.png' },
    { nombre: 'Wii Fit Trainer', img: '/personajes/smash/wii-fit-trainer.png' },
    { nombre: 'Wolf', img: '/personajes/smash/wolf.png' },
    { nombre: 'Yoshi', img: '/personajes/smash/yoshi.png' },
    { nombre: 'Young Link', img: '/personajes/smash/young-link.png' },
    { nombre: 'Zelda', img: '/personajes/smash/zelda.png' },
    { nombre: 'Zero Suit Samus', img: '/personajes/smash/zero-suit-samus.png' },
  ],
  sf6: [
    { nombre: 'A.K.I.', img: '/personajes/sf6/a-k-i.png' },
    { nombre: 'Akuma', img: '/personajes/sf6/akuma.png' },
    { nombre: 'Blanka', img: '/personajes/sf6/blanka.png' },
    { nombre: 'Cammy', img: '/personajes/sf6/cammy.png' },
    { nombre: 'Chun-Li', img: '/personajes/sf6/chun-li.png' },
    { nombre: 'Dee Jay', img: '/personajes/sf6/dee-jay.png' },
    { nombre: 'Dhalsim', img: '/personajes/sf6/dhalsim.png' },
    { nombre: 'E. Honda', img: '/personajes/sf6/e-honda.png' },
    { nombre: 'Ed', img: '/personajes/sf6/ed.png' },
    { nombre: 'Elena', img: '/personajes/sf6/elena.png' },
    { nombre: 'Guile', img: '/personajes/sf6/guile.png' },
    { nombre: 'Jamie', img: '/personajes/sf6/jamie.png' },
    { nombre: 'JP', img: '/personajes/sf6/jp.png' },
    { nombre: 'Juri', img: '/personajes/sf6/juri.png' },
    { nombre: 'Ken', img: '/personajes/sf6/ken.png' },
    { nombre: 'Kimberly', img: '/personajes/sf6/kimberly.png' },
    { nombre: 'Lily', img: '/personajes/sf6/lily.png' },
    { nombre: 'Luke', img: '/personajes/sf6/luke.png' },
    { nombre: 'M. Bison', img: '/personajes/sf6/m-bison.png' },
    { nombre: 'Mai', img: '/personajes/sf6/mai.png' },
    { nombre: 'Manon', img: '/personajes/sf6/manon.png' },
    { nombre: 'Marisa', img: '/personajes/sf6/marisa.png' },
    { nombre: 'Rashid', img: '/personajes/sf6/rashid.png' },
    { nombre: 'Ryu', img: '/personajes/sf6/ryu.png' },
    { nombre: 'Terry', img: '/personajes/sf6/terry.png' },
    { nombre: 'Zangief', img: '/personajes/sf6/zangief.png' },
  ],
  tekken: [
    { nombre: 'Alisa', img: '/personajes/tekken/alisa.png' },
    { nombre: 'Anna', img: '/personajes/tekken/anna.png' },
    { nombre: 'Asuka', img: '/personajes/tekken/asuka.png' },
    { nombre: 'Azucena', img: '/personajes/tekken/azucena.png' },
    { nombre: 'Bryan', img: '/personajes/tekken/bryan.png' },
    { nombre: 'Claudio', img: '/personajes/tekken/claudio.png' },
    { nombre: 'Clive', img: '/personajes/tekken/clive.png' },
    { nombre: 'Devil Jin', img: '/personajes/tekken/devil-jin.png' },
    { nombre: 'Dragunov', img: '/personajes/tekken/dragunov.png' },
    { nombre: 'Eddy', img: '/personajes/tekken/eddy.png' },
    { nombre: 'Feng', img: '/personajes/tekken/feng.png' },
    { nombre: 'Heihachi', img: '/personajes/tekken/heihachi.png' },
    { nombre: 'Hwoarang', img: '/personajes/tekken/hwoarang.png' },
    { nombre: 'Jack-8', img: '/personajes/tekken/jack-8.png' },
    { nombre: 'Jin', img: '/personajes/tekken/jin.png' },
    { nombre: 'Jun', img: '/personajes/tekken/jun.png' },
    { nombre: 'Kazuya', img: '/personajes/tekken/kazuya.png' },
    { nombre: 'King', img: '/personajes/tekken/king.png' },
    { nombre: 'Kuma', img: '/personajes/tekken/kuma.png' },
    { nombre: 'Lars', img: '/personajes/tekken/lars.png' },
    { nombre: 'Law', img: '/personajes/tekken/law.png' },
    { nombre: 'Lee', img: '/personajes/tekken/lee.png' },
    { nombre: 'Leo', img: '/personajes/tekken/leo.png' },
    { nombre: 'Leroy', img: '/personajes/tekken/leroy.png' },
    { nombre: 'Lidia', img: '/personajes/tekken/lidia.png' },
    { nombre: 'Lili', img: '/personajes/tekken/lili.png' },
    { nombre: 'Nina', img: '/personajes/tekken/nina.png' },
    { nombre: 'Panda', img: '/personajes/tekken/panda.png' },
    { nombre: 'Paul', img: '/personajes/tekken/paul.png' },
    { nombre: 'Raven', img: '/personajes/tekken/raven.png' },
    { nombre: 'Reina', img: '/personajes/tekken/reina.png' },
    { nombre: 'Shaheen', img: '/personajes/tekken/shaheen.png' },
    { nombre: 'Steve', img: '/personajes/tekken/steve.png' },
    { nombre: 'Victor', img: '/personajes/tekken/victor.png' },
    { nombre: 'Xiaoyu', img: '/personajes/tekken/xiaoyu.png' },
    { nombre: 'Yoshimitsu', img: '/personajes/tekken/yoshimitsu.png' },
    { nombre: 'Zafina', img: '/personajes/tekken/zafina.png' },
  ],
  lol: [
    { nombre: 'Ahri', img: '/personajes/lol/ahri.png' },
    { nombre: 'Akali', img: '/personajes/lol/akali.png' },
    { nombre: 'Camille', img: '/personajes/lol/camille.png' },
    { nombre: 'Darius', img: '/personajes/lol/darius.png' },
    { nombre: 'Ezreal', img: '/personajes/lol/ezreal.png' },
    { nombre: 'Garen', img: '/personajes/lol/garen.png' },
    { nombre: 'Jinx', img: '/personajes/lol/jinx.png' },
    { nombre: 'Kai\'Sa', img: '/personajes/lol/kai-sa.png' },
    { nombre: 'Katarina', img: '/personajes/lol/katarina.png' },
    { nombre: 'Lee Sin', img: '/personajes/lol/lee-sin.png' },
    { nombre: 'Leona', img: '/personajes/lol/leona.png' },
    { nombre: 'Lux', img: '/personajes/lol/lux.png' },
    { nombre: 'Master Yi', img: '/personajes/lol/master-yi.png' },
    { nombre: 'Miss Fortune', img: '/personajes/lol/miss-fortune.png' },
    { nombre: 'Morgana', img: '/personajes/lol/morgana.png' },
    { nombre: 'Riven', img: '/personajes/lol/riven.png' },
    { nombre: 'Sett', img: '/personajes/lol/sett.png' },
    { nombre: 'Teemo', img: '/personajes/lol/teemo.png' },
    { nombre: 'Thresh', img: '/personajes/lol/thresh.png' },
    { nombre: 'Vayne', img: '/personajes/lol/vayne.png' },
    { nombre: 'Viego', img: '/personajes/lol/viego.png' },
    { nombre: 'Yasuo', img: '/personajes/lol/yasuo.png' },
    { nombre: 'Yone', img: '/personajes/lol/yone.png' },
    { nombre: 'Zed', img: '/personajes/lol/zed.png' },
  ],
  valorant: [
    { nombre: 'Astra', img: '/personajes/valorant/astra.png' },
    { nombre: 'Breach', img: '/personajes/valorant/breach.png' },
    { nombre: 'Brimstone', img: '/personajes/valorant/brimstone.png' },
    { nombre: 'Chamber', img: '/personajes/valorant/chamber.png' },
    { nombre: 'Clove', img: '/personajes/valorant/clove.png' },
    { nombre: 'Cypher', img: '/personajes/valorant/cypher.png' },
    { nombre: 'Deadlock', img: '/personajes/valorant/deadlock.png' },
    { nombre: 'Fade', img: '/personajes/valorant/fade.png' },
    { nombre: 'Gekko', img: '/personajes/valorant/gekko.png' },
    { nombre: 'Harbor', img: '/personajes/valorant/harbor.png' },
    { nombre: 'Iso', img: '/personajes/valorant/iso.png' },
    { nombre: 'Jett', img: '/personajes/valorant/jett.png' },
    { nombre: 'KAY/O', img: '/personajes/valorant/kay-o.png' },
    { nombre: 'Killjoy', img: '/personajes/valorant/killjoy.png' },
    { nombre: 'Miks', img: '/personajes/valorant/miks.png' },
    { nombre: 'Neon', img: '/personajes/valorant/neon.png' },
    { nombre: 'Omen', img: '/personajes/valorant/omen.png' },
    { nombre: 'Phoenix', img: '/personajes/valorant/phoenix.png' },
    { nombre: 'Raze', img: '/personajes/valorant/raze.png' },
    { nombre: 'Reyna', img: '/personajes/valorant/reyna.png' },
    { nombre: 'Sage', img: '/personajes/valorant/sage.png' },
    { nombre: 'Skye', img: '/personajes/valorant/skye.png' },
    { nombre: 'Sova', img: '/personajes/valorant/sova.png' },
    { nombre: 'Tejo', img: '/personajes/valorant/tejo.png' },
    { nombre: 'Veto', img: '/personajes/valorant/veto.png' },
    { nombre: 'Viper', img: '/personajes/valorant/viper.png' },
    { nombre: 'Vyse', img: '/personajes/valorant/vyse.png' },
    { nombre: 'Waylay', img: '/personajes/valorant/waylay.png' },
    { nombre: 'Yoru', img: '/personajes/valorant/yoru.png' },
  ],
  pokemon: [
    { nombre: 'Charizard ex', img: '/personajes/pokemon/charizard.png' },
    { nombre: 'Dragapult ex', img: '/personajes/pokemon/dragapult.png' },
    { nombre: 'Gardevoir ex', img: '/personajes/pokemon/gardevoir.png' },
    { nombre: 'Gholdengo', img: '/personajes/pokemon/gholdengo.png' },
    { nombre: 'Iron Hands', img: '/personajes/pokemon/iron-hands.png' },
    { nombre: 'Klawf', img: '/personajes/pokemon/klawf.png' },
    { nombre: 'Lost Box', img: '/personajes/pokemon/comfey.png' },
    { nombre: 'Lugia', img: '/personajes/pokemon/lugia.png' },
    { nombre: 'Mewtwo ex', img: '/personajes/pokemon/mewtwo.png' },
    { nombre: 'Miraidon', img: '/personajes/pokemon/miraidon.png' },
    { nombre: 'Ogerpon', img: '/personajes/pokemon/ogerpon.png' },
    { nombre: 'Pikachu ex', img: '/personajes/pokemon/pikachu.png' },
    { nombre: 'Raging Bolt', img: '/personajes/pokemon/raging-bolt.png' },
    { nombre: 'Roaring Moon', img: '/personajes/pokemon/roaring-moon.png' },
    { nombre: 'Snorlax Stall', img: '/personajes/pokemon/snorlax.png' },
    { nombre: 'Terapagos ex', img: '/personajes/pokemon/terapagos.png' },
  ],
}
